# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
addons:
  apt:
    packages:
        - asciidoc
cache: packages
r_packages:
    - testthat
    - RUnit
r_github_packages:
    - jimhester/covr
after_success:
    - Rscript -e 'covr::codecov(path = ".", function_exclusions = "\\.onLoad")'
